### PR TITLE
Closes #180

### LINKED ISSUE #180: CSV Upload
CSV upload sometimes fails (after saving in Excel?)

### PR DESCRIPTION
**Pull request by ghost**
csv upload works if user saves csv after opening file in Excel

### CODE REVIEW

File: src/app/core/file-upload/file-upload.component.ts [hunk 1]
```diff
@@ -51,6 +51,7 @@ export class FileUploadComponent {
     //check file extension
     let filetype = this.file.type;
     if (filetype == 'text/csv') {
+      console.log('file is a csv');
```
Comment (lprivette) [inline src/app/core/file-upload/file-upload.component.ts]:
```suggestion
```

**Review by lprivette — APPROVED** [review]
